coverage:
  ignore:
    - "cmd"
    - "cmdline"
    - "config"
    - "event"
    - "errors"
    - "http"
    - "httputil"
    - "humanize"
    - "osx"
    - "reqid"
    - "rpc"
    - "shell"
    - "stream"
    - "stringslice"
    - "test"
    - "time"
    - "ts"
    - "token"
    - "url"
    - "xgo"
    - "xlog"
